### ISSUE TITLE
Default filter

### ISSUE THREAD

**Issue by giovanni-giovannozzi-ocs** [Quitten/Autorize#101]
In interception_filters.py the line 
self._extender.IFModel.addElement("URL Not Contains (regex): \\.js|\\.css|\\.png|\\.jpg|\\.svg|\\.jpeg|\\.gif|\\.woff|\\.map|\\.bmp|\\.ico$")
should be
 self._extender.IFModel.addElement("URL Not Contains (regex): (\\.js|\\.css|\\.png|\\.jpg|\\.svg|\\.jpeg|\\.gif|\\.woff|\\.map|\\.bmp|\\.ico)$")
Otherwise the $ (end with) will be applied only to the last element (.ico).
Written without parenthesis the filter also escludes .jsp, because it contains .js.

**Comment by Quitten** [comment]
Fixed on d04469b3daf3db3b3aed6311e4e382a2f4954bb4
Thanks for reporting
