### ISSUE TITLE
Exception “0d 0a” 

### ISSUE THREAD

**Issue by idlefire** [Quitten/Autorize#102]
The modified request package will add a line of `0d 0a` resulting in a request error
Original
![image](https://user-images.githubusercontent.com/18007341/196994692-8775829b-6a00-482e-9747-8a4b69ec8f42.png)
Modified
![image](https://user-images.githubusercontent.com/18007341/196994820-82117d4c-b38d-4110-b018-9eaadcdc66dc.png)
![image](https://user-images.githubusercontent.com/18007341/196994870-3004955d-9270-47f9-9479-a959fd0fede4.png)

**Comment by Quitten** [comment]
@idlefire - I cannot reproduce it, can you share some details about your setup? (operating system, autorize version, etc.)

**Comment by terminalJunki3** [comment]
@idlefire @Quitten for what it's worth, I fixed a similar issue in this codebase issue #84.  Just in case they are using the current repo.

**Comment by Quitten** [comment]
@idlefire  - closed for now, will reopen in case we will be able to reproduce
