### ISSUE TITLE
Headers are case-sensitive

### ISSUE THREAD

**Issue by irsdl** [Quitten/Autorize#106]
As per HTTP standard, headers are case-insensitive (see https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive). However, when a header such as `Authorization` is provided, the application does not replace the `authorization` header which starts with a lowercase letter. As a result, the modified request will contain 2 authorization headers instead of replacing the original one.

**Comment by Quitten** [comment]
True that, according to RFC headers are case-insensitive.
https://github.com/Quitten/Autorize/pull/107
Merged, thank you very much for contributing.
Closed.
