### ISSUE TITLE
Interception Filters feature 

### ISSUE THREAD

**Issue by asuspctow** [Quitten/Autorize#116]
Hey Mr. Barak,

I wish you a happy work day. I will contact you regarding the wonderful Autorize add-on. I would like to suggest some improvements based on the problems I encountered. I am looking to add a feature that allows importing the filter for both "Contain Link&Not Contain Link". I think if there was an option that allowed me to export and import the filter, it would save me a lot of time instead of re-entering all the links that I do not want every time, and their number may sometimes reach more than 100 endpoints.

Therefore, I would like to ask you to add this option, or if you would please guide me to some sources on how to develop this option and add it to your plugin.

my regards

**Comment by Quitten** [comment]
Hey @asuspctow - Im quite confused.
Are you requesting a filter that called "Contain Link&Not Contain Link"? or you referring to an existing filter? because there is no such filter.
Or you talking about importing filters? you have regex filters that you can use it for multiple values.
Let me know what do you think

**Comment by Quitten** [comment]
Got it, can you please give more concrete example? I wonder id this can be done via regex anyway.
And generally speaking you can use regex or statement

**Comment by Quitten** [comment]
Yes, there is a way.
You can use the `URL Not Contains (regex)` interception filter, and use pipe (|) in order to filter multiple endpoints on the same filter as the following value:
```
(/gateway/api/pubsub/subscribe|/rest/internal/latest/connect/data/dialog|/wiki/rest/jiraanywhere/1.0/servers|/gateway/api/emoji/|/rest/internal/2/log/unsafe/frontend-exception|/images/icons/priorities|/wiki/plugins/servlet/ac/css-style)
```

Let me know if this solve your need

**Comment by asuspctow** [comment]
Hi @Quitten 

Thank you very much this works well. Have a happy work day. Thank you very much for the help.

Best,
