### ISSUE TITLE
Manual Install Step 5 Error

### ISSUE THREAD

**Issue by mrbbking** [Quitten/Autorize#118]
Step 5 is, "Download the Autorize.py file." but that's not enough.

Burp needs the whole project to go along with it.

Suggested re-phrase of Step 5:

"Clone the repository or download it and unzip the file"

**Comment by Quitten** [comment]
Fixed on [c9bc4f2](https://github.com/Quitten/Autorize/commit/c9bc4f2f81aa256ad664b67ac75497bbcdb7fb14) thanks!
