### ISSUE TITLE
window resize issue in burpsuite

### ISSUE THREAD

**Issue by 0p71mu5** [Quitten/Autorize#125]
after burp's latest update, unable to resize autorize configuration window due to UI elements.
tested on burp 2024.7.6

**Comment by Quitten** [comment]
Duplicates https://github.com/Quitten/Autorize/issues/123
Fixed in [bd24b12](https://github.com/Quitten/Autorize/commit/bd24b12c49a3ef3aebfd6863d02472949f84ef25)
Merged to BApp store at https://github.com/PortSwigger/autorize/pull/14 version v1.8.1
