### ISSUE TITLE
Match/Replace delete filter

### ISSUE THREAD

**Issue by va-14** [Quitten/Autorize#127]
I'm not able to delete my filters, I'm using Burp Suite Professional v2024.9.3 on a MacOs 15.0.1 
![Screenshot 2024-10-29 at 11 18 42](https://github.com/user-attachments/assets/d036820d-4f81-40c6-ae8e-de1be89292f6)

**Comment by Quitten** [comment]
On it.

**Comment by Quitten** [comment]
@va-14 - I just pushed [f3028ba](https://github.com/Quitten/Autorize/commit/f3028ba6861729c824496a26759ba0b532a202bd) that should fix the issue, can you please verify?

**Comment by va-14** [comment]
Verified, the buttons are now below. Thanks for the quick fix!

**Comment by Quitten** [comment]
@va-14  - I pushed 527ddd32639f43d1ab40fd97243d52465ba1f478 to fix this, but for some reason its not working properly, I dont have time to debug it right now, will be happy to get someone's help.
Closing this for now as this issue has been fixed.
