### ISSUE TITLE
Exclude the URI from Headers Match/Replace Configuration

### ISSUE THREAD

**Issue by zy9ard3** [Quitten/Autorize#132]
The Match/Replace configuration for Headers are including URI and if we set to replace a value on Headers, the values are being replaced on URI also

##### Example Request :

```http
GET /api/v1/team/175a49f8-1cf1-4b67-91c9-dfac105fadd5/metadata HTTP/2
Host: api.example.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
X-Team-ID: 175a49f8-1cf1-4b67-91c9-dfac105fadd5
Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxx
```

Here I only want to replace the value of `X-Team-ID`, but when I set this in `Match/replace` as `Match/Replace`=>`Headers(simple string)`=>`set value`, the value in URI is also being replaced with the set value

**Comment by Quitten** [comment]
@zy9ard3 - Thanks for reporting! fixed on [c273cbc](https://github.com/Quitten/Autorize/commit/c273cbc34599fc08e9a39d4106f8521b43d0b2c9)
