### ISSUE TITLE
Repeat requests button

### ISSUE THREAD

**Issue by xmendez** [Quitten/Autorize#14]
Hi,

It would be great to be able to repeat a selection and/or all the requests using a modified configuration. For example, if you want to retest and the session identifier has changed or you are repeating the exact same requests with a different user role (with a different session).

Thanks for the extension, keep the good job!

cheers

**Comment by Quitten** [comment]
Done, via commit bf23f41
Let me know that it works on your machine properly and i'll close the issue.

**Comment by xmendez** [comment]
That was fast! It would be more usable if you could select more requests at the same time.

**Comment by Quitten** [comment]
Thanks, for now i'll close the issue because it solved.
Due to lack of time i improve this feature more, but i'll keep it in mind.
In addition you can develop it by yourself and send a pull request and i will check it out.
