### ISSUE TITLE
Results window becomes quickly cluttered

### ISSUE THREAD

**Issue by codingo** [Quitten/Autorize#15]
# Problem Statement

Authorize doesn't implement filters like the proxy and target tabs do meaning that large amounts of data (such as a shodan request from an extension) end up windows. Limiting to scope is an option, but this is often flexible and changing in scope aren't reflected post-addition in Authorize.

# Proposed Solution

Addition of filters to the results window in the same manner as Proxy or Target.

**Comment by Quitten** [comment]
@codingo I just pushed https://github.com/Quitten/Autorize/commit/ab9aa2d403a3315d3a7850e78895313110c7b0cd allows you to set an interception filter which ignoring spider/proxy/target requests.

**Comment by codingo** [comment]
This is excellent, thank-you
