### ISSUE TITLE
Unable to delete items from results

### ISSUE THREAD

**Issue by codingo** [Quitten/Autorize#16]
The ability to delete results from authorize in bulk would make cleaning through results much more efficient. Typically I will end up with some incorrect results when setting up my regular expressions that then get in the way when trying to sort by columns for bypassed successful logins later. It would be great to run some tests, delete the bad results and then start my testing.

**Comment by Quitten** [comment]
Is the 'Clear list' button is not enough? would you like to be able to remove specific fields? like via right click -> delete?
In addition, in case you would like to DIY, just send a pull request and let me know :)

**Comment by codingo** [comment]
Yes, thinking more right click - delete. It would make filtering results (by removing junk) much more efficient in large tests.

**Comment by Quitten** [comment]
@codingo - I tried to implement this feature but I didnt have enough time to finish it, I currently pushed https://github.com/Quitten/Autorize/commit/d93fd7490cfbfc5fed9ed9b38ba991b25300abff#diff-370c88cf0195bbc74583252c05ef49bcR1384 but there is a bug on line 1384. if you would like to help :)

**Comment by terminalJunki3** [comment]
Just added a PR but I think I think I have a working solution.  Let me know if you see any bugs.

**Comment by terminalJunki3** [comment]
@codingo @Quitten Was able to implement the multi-row select. You should now be able to select multiple rows by holding control and delete them. This should satisfy this request and this request should be able to be closed out.

**Comment by Quitten** [comment]
Reviewed and tested, merged.
Thank you very much for contributing!
