### ISSUE TITLE
Ability to run Authorize on spidered requests

### ISSUE THREAD

**Issue by codingo** [Quitten/Autorize#17]
Authorize would be significantly more useful if I could spider an application with Authorize running to then review all of the results. Understandably this would be quite "noisy" and resource heavy so having it disabled by default would be recommended.

**Comment by Quitten** [comment]
@codingo I just push https://github.com/Quitten/Autorize/commit/237689d90e4579f018d606a9313f7a7195d4fb2b so Autorize will avoid spider traffic by default, thanks :+1:

**Comment by codingo** [comment]
Perfect, thank-you!
