### ISSUE TITLE
Setting to automatically capture cookies from the last request

### ISSUE THREAD

**Issue by codingo** [Quitten/Autorize#18]
Often I'm changing accounts and just want to leave Authorize on in the background to revisit later for an easy "gotcha". This method works, but if I change accounts midway through a test and forget to go to authorize and recapture cookies then my test case falls apart.

A setting to automatically capture cookies on the last user driven request to perform tests against would greatly enhance this functionality.

**Comment by Quitten** [comment]
Nice idea! but I think it is better to add a tab/window that allows you actually "save" cookies and name them, like "admin" or "low-previllieged user" cookies, then you will be able to click on the relevant user and it will automatically will set the relevant header for you.
Let me know what do you think about that.

**Comment by Quitten** [comment]
Just pushed https://github.com/Quitten/Autorize/commit/d93fd7490cfbfc5fed9ed9b38ba991b25300abff which allows you do what I described above, closing this issue, let me know if you think different :)

**Comment by codingo** [comment]
Just had a play around with this - I agree with the change. Thank-you!
