### ISSUE TITLE
Requests not analysed

### ISSUE THREAD

**Issue by geekscrapy** [Quitten/Autorize#19]
I've got a fairly standard setup with Burp however requests are not being added to the list automatically. However if I add to the list with the context menu it will be analysed.

Running Burp Pro v1.7.29

**Comment by Quitten** [comment]
Can you be more specific? whar exactly are you doing? just turn on Autorize and see nothing?
are the requests are itercepted on burp? did you check the interception filters? there is a chance that the default one blocking your specific requests

**Comment by Quitten** [comment]
@geekscrapy closing this issue until you will explain
