### ISSUE TITLE
Header not replaced, but added at the end

### ISSUE THREAD

**Issue by 181hackerone181** [Quitten/Autorize#21]
Hello,

First of all thank you for the awesome plugin. I have just a problem with it. Let's say I need to replace the cookies and add a CSRF header in Configuration. This successfully replaces the cookies and adds the new header at the end, but the initial header is still in the request... A concrete example of the Configuration 

```
Cookie: periscope_domain_id=value; periscope_domain_experiment=; periscope_session=session value;
X-CSRF-Token: YXB8ZV+vTgNh8wdhpN6Ms1qyED+J4rkMR+hjCI4PV8GXP+eW8ZAU/eswvQ0UiJutp18K1dZsXFn3xqmQLynSJA==
```

The modified request looks like this 

```
Host: HOST
/**/
X-CSRF-Token: IrnhXEROIJid8zfzyuyg8nq5JrVhlWVtD5VSZnPPN4q81+w6fXOGllvNSRmnYJOvWv9uG3jVKCAXbVe4tx6Vkg==
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
/**/
Cookie: periscope_domain_id=value; periscope_domain_experiment=; periscope_session=session value;
X-CSRF-Token: YXB8ZV+vTgNh8wdhpN6Ms1qyED+J4rkMR+hjCI4PV8GXP+eW8ZAU/eswvQ0UiJutp18K1dZsXFn3xqmQLynSJA==
```

As you can see the first X-CSRF-Token is incorrect and the second one is the correct one. Could I do anything to solve this ?

**Comment by barakt11** [comment]
Hey, it has been solved at the previous commit (https://github.com/Quitten/Autorize/commit/da5133f180973e2711d073d55e81962560b001f8), please update your Autorize plugin.
Let me know if something going wrong.

**Comment by Quitten** [comment]
Hey, it has been solved at the previous commit (https://github.com/Quitten/Autorize/commit/da5133f180973e2711d073d55e81962560b001f8), please update your Autorize plugin.
Let me know if something going wrong.

**Comment by Sjord** [comment]
This works for me.

**Comment by Quitten** [comment]
Great!
