### ISSUE TITLE
Right click: Send to Repeater

### ISSUE THREAD

**Issue by andresriancho** [Quitten/Autorize#24]
When I'm trying to confirm an autorize finding I want to re-send the modified request. I was expecting to be able to right click on the HTTP request, have the usual context menu that Burp shows, and choose "Send to repeater". Nothing shows up when I right click over the HTTP request.

**Comment by Quitten** [comment]
@andresriancho - I hope I will have time to do that in the next months, I was fixing other issues - checkout the last commits.
You are more than welcome to DIY and send me a PR for that.

**Comment by Regala** [comment]
Nevermind, created a pull request #29 to fix this :)

**Comment by Quitten** [comment]
Closed, @Regala  - thanks for the PR :)
