### ISSUE TITLE
Colon in filter not working

### ISSUE THREAD

**Issue by ismisepaul** [Quitten/Autorize#25]
When there is a colon in a filter the filter does not work. When editing the filter everything after the colon is deleted. This is needed for JSON responses.

Filter applied (always shows bypassed)
![image](https://user-images.githubusercontent.com/912403/42998361-ce68eea2-8c11-11e8-9f1b-e750cd4a31ff.png)

Filter being modified (everything after colon removed)
![image](https://user-images.githubusercontent.com/912403/42998377-e113e61a-8c11-11e8-8c80-96d9075ad2f5.png)

Also tried using regex with the same results (even escaping colon)

**Comment by Quitten** [comment]
commited https://github.com/Quitten/Autorize/commit/5dd61e1c25a0ec2ab77dd01cdf1869ffea2ce415 for modify filter bug.
let me know if the filter is still not working

**Comment by Quitten** [comment]
@ismisepaul - I will assume that it helped :)

**Comment by ismisepaul** [comment]
Thank you yeah that helped 👍
