### ISSUE TITLE
Interception filter disappears after modification

### ISSUE THREAD

**Issue by henshin** [Quitten/Autorize#31]
Noticed a bug on the interception filter behaviour. Here are the steps to reproduce:
1. On the interception filters, click one of the preset filters and click "Modify". 
2. Modify the filter
3. Add filter
4. Click the modified filter on the filter list
5. Click modify again.

Expected result: the filter would be copied to the Content section to allow modification again.
Current result: The filter is deleted.

Let me know if you need any further info.

**Comment by Quitten** [comment]
@henshin - Can you please send the exact filter you are using? type + content, it work properly for me

**Comment by henshin** [comment]
It seems that the issue is that when we click the rule we want to modify, it doesn't automatically selects the appropriate type associated with that rule. So taking the default extension filter as an example, the steps I've described above add a rule of the type "Scope Items only" instead of the "URL Not Contains (regex)" associated with that rule. That somehow makes it invalid for the second time we try to modify it.

**Comment by Quitten** [comment]
@henshin - this bug fixed in https://github.com/Quitten/Autorize/commit/2a61ae8950f824d8b50d364660c81d2403cc955d?diff=unified#diff-370c88cf0195bbc74583252c05ef49bcR630
Please let me know if you have any comments
