### ISSUE TITLE
Feature Request: Send to Comparer

### ISSUE THREAD

**Issue by ramimac** [Quitten/Autorize#36]
Similarly to #24 I'd love to be able to right click and "Send responses to comparer." This is frequently my workflow anyway.

The implementation should be very similar to #24 -- if I get a chance I'll open a PR mostly cribbing off https://github.com/Quitten/Autorize/pull/29/commits/27c8026691f020356681659ae4a3de94025dc77e -- just using <https://portswigger.net/burp/extender/api/burp/IBurpExtenderCallbacks.html#sendToComparer(byte[])>

**Comment by Quitten** [comment]
Sounds legit, I will try to find some time to do so, if you can create PR it would be great, if not, give me couple of weeks and it will be done :)
