### ISSUE TITLE
Optional Support of other HTTP methods(PATCH,PUT,DELETE)

### ISSUE THREAD

**Issue by gk0us** [Quitten/Autorize#38]
A nice thing to have would be to be able to select the HTTP methods that Autorize will be replaying (e.g. from the configuration tab) as well as support for methods other than POST/GET/OPTIONS. 

At the moment, I don't think that patch is supported(at least in the BApp version).

**Comment by gk0us** [comment]
Great man! Thanks, that's what I was talking about. Now that I think about it, the opposite(blacklist /excluding methods) would also be useful. E.g. in case of apps that send a huge amount of OPTIONS requests and you want to exclude only these, without having to enumerate listing all the other methods

The HTTP versions are indeed supported, I just checked. Weird, I am pretty sure that PATCH was not going to the log last time I tried. Must have been something else that was breaking it.

**Comment by Quitten** [comment]
787ca79 resolving this, let me know in case you have any comments. Closed.
