### ISSUE TITLE
Only attack burp scope

### ISSUE THREAD

**Issue by NeuronAddict** [Quitten/Autorize#46]
When scanning a target, it will be great to have the possibility to limit the scan to the suite scope to not actively scan any out-of-scope target.

For example, when using firefox and scanning an in-scope domain, the plugin will send requests to other domains (plugins services, version-check, ...) and this is not what is expected by the user. It can cause legal issues during a pentest.

**Comment by Quitten** [comment]
Hey, thanks for the heads up!
Will investigate this and update.

**Comment by Quitten** [comment]
@NeuronAddict - I just tested the scope only interception filter, and it seems to work properly.
Can you please elaborate how did you experienced the described above? and how to reproduce?

**Comment by Quitten** [comment]
Closed due to lack of comments.

**Comment by NeuronAddict** [comment]
Hi,

Sorry for the delay response.  Its my mistake, filter work like a charm.

Thanks
