### ISSUE TITLE
Feature Request: Authorization Header

### ISSUE THREAD

**Issue by itsallmathematics** [Quitten/Autorize#48]
I'm pretty new to Autorize, but have enjoyed the tool a lot. If this feature already exists, please correct me, but one thing I've noticed is that when I test APIs, Authorize will only modify the tokens in the `Cookie:` field. However, it does not modify the `Authorization` header field and thus does not test for IDOR or other access control issues on requests which use the `Authorization: BEARER` style token header. For example, I tested a service where Autorize successfully replaced the cookies in the request but the Authorization header contained the current user's OAuth token rather than the lower privilege user's. I tried the Match/Replace feature by matching on the Authorization header and replacing with lower privilege auth header but this didn't seem to work. Maybe I misunderstand this feature. If this is something I could contribute, let me know.

Thanks.

**Comment by Quitten** [comment]
closing due to lack of comment, you are free to reply and reopen in case you think its still an issue
