### ISSUE TITLE
Authorization won't work.

### ISSUE THREAD

**Issue by chanpu9** [Quitten/Autorize#51]
I used a Burp version 2020.4 and 2020.5. I could not send any request or cookie to Authorization plugin. Please verify and fix the issue.

**Comment by Quitten** [comment]
Hey, can you please share more details?
It seems to be working properly on 2020.4.1
Can you share some error logs?

**Comment by chanpu9** [comment]
I tried to send the request to Authorization by right click on the request then choose "send to Authorization". That request won't show in Authorization.

**Comment by Quitten** [comment]
Thanks for the report, fixed on a070e923f9e03f22a1828fd2b4679ff8c457a81e.
