### ISSUE TITLE
Filter to overrule bypass state

### ISSUE THREAD

**Issue by roman-mueller** [Quitten/Autorize#53]
As far as I understand the "Enforcement Detector" filter is only used on items that are in "is enforced???" state. 
It would be great to have a filter which also gets applied to items detected as "Bypassed!".

My case is this, sites which are heavily using 302 redirects are producing a large number of false positives.
A valid request gets 302 redirected to /$uuid/whatever, while the modified ones get 302 redirected to /login. This currently is detected as bypassed.

I would love to have a filter that specifies "whenever a 'Location: /login' Header is found, the state is enforced".

**Comment by Quitten** [comment]
Hey, thanks for opening this issue, the filter "Headers (simple string)" suppose to give you this ability:
![image](https://user-images.githubusercontent.com/8288210/85220601-9a747f80-b3b5-11ea-941c-50c81852397a.png)


For some reason, seems like we have a bug and its not working properly, I will fix it and update.
Thanks again :+1:

**Comment by Quitten** [comment]
Seems like everything is working properly after checking it on my side, I used the `Headers` enforcement detector filter as described above.
As you can see, without the headers filter it looking like:
![image](https://user-images.githubusercontent.com/8288210/85222912-4f636800-b3c7-11ea-8f4a-721c21c56651.png)

and then I added the headers filter and it worked as expected and labeled it as enforced:
![image](https://user-images.githubusercontent.com/8288210/85222926-62763800-b3c7-11ea-969a-46f22032b8b0.png)

Please let me know there is something I missed
In case there will be no reply in few days, I will close this issue.
Thanks!

**Comment by roman-mueller** [comment]
But is this working if the initial detection is in "Bypassed!" state?
In your example the filter changed the "Is enforced???" to "Enforced!".
In my example it would be from "Bypassed!" to "Enforced!".

Also, in my case the length of all 3 requests was the same (0), not sure if this changes anything though.

**Comment by Quitten** [comment]
Hey, thanks for raising up this issue!
The previous implementation was that in case status code and length was the same, filters were not applied.
Now, the enforcement filters runs first, and only in case we have no indicators from it, we check the content-lenght.
Fixed in 34a42b6b3df3d571efa3bad8fa4f9216a87f661b
Enjoy!
