### ISSUE TITLE
Removing cookies already configured

### ISSUE THREAD

**Issue by Soldat-Ryan** [Quitten/Autorize#55]
Hi!
Thanks for this great extension!
How can I remove headers already configured in the interface ?
Actually, I have to reinstall the extension to remove them.

Is there a feature available ?
Thx

**Comment by Quitten** [comment]
Hi @Soldat-Ryan,
Currently, there is no way to remove saved headers, I would need to implement it, hope to find time soon
If you want to contribute, all you need is to add more button like the [saved headers](https://github.com/Quitten/Autorize/blob/a5f0052840ce209530ea90e874679b1be9989911/gui/configuration_tab.py#L49) and add the functionality to remove it from the savedHeaders object the opposite of [save headers function](https://github.com/Quitten/Autorize/blob/a5f0052840ce209530ea90e874679b1be9989911/gui/configuration_tab.py#L116)

Thank you for the great feedback glad to help the community!

**Comment by Quitten** [comment]
@Soldat-Ryan - I implemented the remove button feature, see d9631d2
Please reply that its all working good :)
Closed.

**Comment by Soldat-Ryan** [comment]
It works like a charm
Thanks a lot for your quick response !
