### ISSUE TITLE
Token in URL parameter

### ISSUE THREAD

**Issue by julianjm** [Quitten/Autorize#56]
Some APIs receive the token via a GET parameter, instead of a request header.

Is it possible to use the Authorize extension in such scenarios?

**Comment by Quitten** [comment]
Everything is possible if you really want :)
I find it valuable to add such feature to the extension, I still need to think about how to implement it clear for users to use
I hope to find time implement it soon
Thanks for the feedback

**Comment by s0i37** [comment]
+

**Comment by Quitten** [comment]
@s0i37 @julianjm - Thanks for the heads up, I just resolved this issue in the commit 2b39756566270b767996a96142c657222810ebfb
All you need to do is simply toggle the "replace query params" checkbox and Autorize will replace the targeted query param.
Let me know if you need any further information.
Closed.
