### ISSUE TITLE
Filter HTTP methods?

### ISSUE THREAD

**Issue by Leezj9671** [Quitten/Autorize#57]
I dont't want to test some HTTP methods, like PUT/DELETE/OPTIONS, but I can't find method filter in menus. How can I filter these methods?

**Comment by Quitten** [comment]
Hey, you can simply do that via interception filter with "Ignore HTTP methods" as following image:
![image](https://user-images.githubusercontent.com/8288210/92392482-04840180-f127-11ea-8efc-543420934bc0.png)

**Comment by Quitten** [comment]
Closing, re-open in case you have any other problem using it, I just checked and it working properly.
