### ISSUE TITLE
No Scrollbar when content is overflowed from the box

### ISSUE THREAD

**Issue by hash3liZer** [Quitten/Autorize#58]
First, of all. Thanks for such an awesome extension. 

When a screen is compact or the screen resolution is low, the content/controls are being overflowed from the respective box and the problem is that no scrollbar is being shown at the time due to which I am unable to access the controls and different buttons. So, it lefts me with very limited functionality. Here's the screenshot of this: 

![Screenshot at 2020-09-08 10-37-18](https://user-images.githubusercontent.com/29171692/92437146-e6201380-f1c3-11ea-9f0c-7872fc4a224b.png)

The button below at the end is not visible and also not accessible.

**Comment by Quitten** [comment]
Hey,
Thanks for your feedback, always happy to hear it's helping the community :)
Regarding the issue, it is a known issue - https://github.com/Quitten/Autorize/issues/10 
I am currently super busy, but I hope to be able to fix this specific instance by adding the possibility to change the panels' height in the next few days/weeks

**Comment by hash3liZer** [comment]
OK, great. Hope to hear from you in next few weeks. Been looking on it for a while now.

**Comment by Quitten** [comment]
@hash3liZer - Thanks for your feedback, fixed in https://github.com/Quitten/Autorize/commit/c521cf04ca1b41c43951e30d725df956708de38e please let me know after you verify its all working well, enjoy!
