### ISSUE TITLE
Fetch cookies upgrade to fetch cookies & tokens

### ISSUE THREAD

**Issue by Greenwolf** [Quitten/Autorize#59]
This more of a feature/upgrade request, but it would be great if Autorize's get cookies also have a button for get Authorisation that covered bearer tokens and basic auth.

**Comment by aress31** [comment]
Agree with @Greenwolf authentication is usually handled by JWT and Authorization Bearer.

**Comment by Quitten** [comment]
Fixed on commit 49b8603f72a35dbc1d66c93309d0a1fb733b593b.
happy hacking :)
