### ISSUE TITLE
Inject full HTTP headers

### ISSUE THREAD

**Issue by 0-duke** [Quitten/Autorize#6]
Hi, I would like to have an option where I can choose if the plugin have to inject just a cookie or a complete header. I found a lot of application with session management made with cookies and HTTP Headers and I would like to continue to use this amazing plugin.

Thanks guys for your work.

**Comment by federicodotta** [comment]
Nice idea. We will work on it in the future!

**Comment by Quitten** [comment]
Hi,
In addition for what federico commented,  in case you would like to help us developing this feature we will be glad to get a pull request and if the code will be written properly i will merge it

**Comment by Quitten** [comment]
Hi, sorry for the wait but can you explain your problem  more? because right now you can inject full HTTP header and/or cookies.

**Comment by pnegry** [comment]
line 1029:

`[removeHeaders.add(x.split(":")[0]) for x in self.replaceString.getText().split("\n")]`

sorry I don't have time to make a full PR, just had to make this work.

**Comment by Quitten** [comment]
@pnegry , didnt understand what exactly you mean, can you please elaborate or perform PR?

**Comment by pnegry** [comment]
No
