### ISSUE TITLE
Batch of Improvement Ideas

### ISSUE THREAD

**Issue by aress31** [Quitten/Autorize#62]
Hi @Quitten 

First of all, you created an amazing extension (a bit upset I discover it just now...)!

As I used it in a real-life scenario, I noticed that a few improvements could be made to make pentesters life easier:

1. Remove duplicate entries, I usually include the CVS output to my penetration test reports, and sometimes, I repeat the same requests multiple times as I am manually crawling/interacting with the web app. That means that I end up with a CSV table with many duplicate entries, giving an option to uniq/sort the view/logs would be awesome.
2. Removing arbitrary rows, I guess that it would not be too hard to implement a feature to give users the possibility to delete specific rows on the view.
3. Live refresh on the view, when setting filters and regex, it would be cool if the view/table was automatically refreshed to leave out the rows not matching the filters.

 These are just a few minor improvements that would make life much easier.

Again, thanks for this amazing extension!

Alex

**Comment by Quitten** [comment]
Hi @aress31 - thanks for the feedback, and i'm honored to help the community with this tool :)

Regarding your points:
1. Agree, we should remove duplicates rows, I hope i'll find time to get it done soon (but I think there are other feature requests to be done prior this one)
2. Same as issue https://github.com/Quitten/Autorize/issues/16
3. I like it, hope to get it done soon

**Comment by terminalJunki3** [comment]
@aress31 I'm willing to spend the time on adding this feature.  If you have a screen shot highlight what you are referring to, ill  look it over.

**Comment by terminalJunki3** [comment]
@Quitten submitted pull request. Feature allows use to check a box to remove duplicates from CSV and HTML report.  [terminalJunki3:removeDuplicates](url)

**Comment by Quitten** [comment]
Closing after merging @terminalJunki3's PR. e658e1ccb1171aa575be659bacae0b2b16df8fa7
@aress31  - Please let me know if you have any further requests.
