### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by dubey-amit** [Quitten/Autorize#65]
Hi,

Authorize works perfectly however, once I click on the table it response is really slow. No matter how many requests are in list.

Using : Burp pro v2021.2.1 in Win 10

**Comment by Quitten** [comment]
@dubey-amit  - can you elaborate more? what kind of Autorize verison? and what do you mean click on table? on one of the items?
Sounds like a problem on your end, do you have any errors on extender tab?

**Comment by Quitten** [comment]
Closed due to inactivity
