### ISSUE TITLE
[Feature request] New Type for the Interception Filters

### ISSUE THREAD

**Issue by Sudistark** [Quitten/Autorize#70]
Hey @Quitten ,

Is there any way to filter requests based upon a string/regex match in the request body?
For eg:
Suppose this an unwanted request , which I don't want to see:

```
POST /api/v2/graphql HTTP/2
Host: localhost:1337
Cookie: 
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 
Content-Type: application/json
Content-Length: 4872
Te: trailers
Connection: close

{
  "operationName": "Usernotification",
  "query": "query Usernotification(}"
}
```

I want to filter all the requests which have the word `Usernotification` in the request body.

Currently these are the only available options in the filter tab:

![Options](https://i.imgur.com/HO1omxz.png)

If there is no way to do it, can you please add more options in the `interception filters` tab for this scenarios:

```
Request Body contains (simple string)
Request Body contains (regex)

Request Body NOT contains (simple string)
Request Body Not contains (regex)

Response Body contains (simple string)
Response Body contains (regex)

Response Body NOT contains (simple string)
Response Body Not contains (regex)
```

PS: I am great fan of this tool, I almost used it daily :) 
Thankyou so much for creating this awesome tool.

**Comment by Quitten** [comment]
Hey @Sudistark,
Thanks for the feature request, I hope to find some time in the next weekend in order to develop these abilities.
Super happy to help the community :)
Keep enjoying the tool

**Comment by Quitten** [comment]
@Sudistark  - I just pushed 2a9f9df9c349524d5b02c59bb02afbd729972da9 to solve this issue.
Please let me know if you have any further issues.
Issue closed.
