### ISSUE TITLE
OPTIONS preflight requests

### ISSUE THREAD

**Issue by drwetter** [Quitten/Autorize#76]
Hi,

thanks for the very useful plugin!

what I miss in the current project is  to ignore OPTIONS requests. They are always labeled as bypassed.  (don't know how the detection works, grepping for 401s and the like?)

I know I can sort by clicking on the column head but then I can't sort for anything else.

Cheers, Dirk

**Comment by Quitten** [comment]
Hi Dirk,
You are welcome :) happy to help the community!

I want to make sure it is clear, you are talking about 2 enhancements:
* OPTIONS to be treated as any other methods
* Sorting the table by something else rather than the columns? can you elaborate?

**Comment by drwetter** [comment]
Hi,

I am talking about two things, yes. 

* to **ignore** OPTIONS request completely. 4 weeks ago I was working with an application which did a lot of preflight requests.  It was kind of annoying to weed them out.
* As said the column heads are fine to sort. But I missed a secondary criteria or a filter in order to go through a larger number of requests. It's getting cumbersome otherwise. It would also help to have a CSV export.

Cheers, Dirk

**Comment by Quitten** [comment]
Hi @drwetter,
I just added new interception filter "Ignore OPTIONS requests" on e98b67a10901d22bc45a29a25dbc60cb3d43208d.
Let me know if it is satisfying your needs.
Closed.

**Comment by drwetter** [comment]
Thanks! Probably next week or so.

Is there a way to trigger (nudge @PortSwiggerSupport) the burpsuite fork of this repo or does that happen automatically?

**Comment by Hannah-PortSwigger** [comment]
Thanks for tagging us!

The update process for the BApp Store requires the author to make a pull request to our fork and drop us an email (support@portswigger.net) to let us know there is an update available.

We can then merge in the changes, build, package, and test the updated extension before releasing it on the BApp Store.

This is detailed on the BApp Store page, and in our "Submitting an extension to the BApp store" documentation.
- https://portswigger.net/bappstore
- https://portswigger.net/burp/documentation/desktop/tools/extender/submit-extension
