### ISSUE TITLE
[BUG] Obey the scope set and don't submit Cookie or Auth header to third parties

### ISSUE THREAD

**Issue by drwetter** [Quitten/Autorize#77]
Hi,

if $BROWSER is updating anything or checking for updates it can run through burp or not. Some may chose to just restrict those requests just by narrowing the scope (in "Target")

In such cases when also "Autorize is on" I have observed that the authentication parameters are submitted to Mozilla, see pic.

![grafik](https://user-images.githubusercontent.com/8036727/138711960-7c966a8a-74a4-4e17-ace1-7699da857668.png)

Cookie and bearer token were automatically + manually defined in the "Configuration" tab

**Comment by Quitten** [comment]
Can you please elaborate more on that? I'm not sure I fully understand that.
Please give more examples and elaborate regarding the expected behaviour

**Comment by Quitten** [comment]
@drwetter - closing due to your inactivity.
