### ISSUE TITLE
Auto Packet Capture not working

### ISSUE THREAD

**Issue by ghost** [Quitten/Autorize#8]
Auto Packet Capture is not working with Red and Green "Autorize button", and it can't automatically load requests .
it just work with "Send request to Autorize"
burp 1.7.03
and autorize is last version of git .

thanks .

**Comment by federicodotta** [comment]
Hi,

can you please send me some details about the bug?

I just triied the plugin and it worked correctly.

Do you have some errors in the plugin error console or in the burp shell? 

If you give me some details about your OS and Java version I try to replicate the issue.

Thank you.

**Comment by federicodotta** [comment]
Have you noticed that there are two default Interception filters? Try also to remote those filters

**Comment by Quitten** [comment]
Closed
