### ISSUE TITLE
Filter by header

### ISSUE THREAD

**Issue by louisatrhymetec** [Quitten/Autorize#80]
Would it be possible to add a filter by header? This would be very useful when doing testing with something like pwnfox, where pwnfox will add header to create container in firefox and color code in proxy. Thought is that you can filter by color of tab in pwnfox.

**Comment by Quitten** [comment]
Fixed at https://github.com/Quitten/Autorize/commit/c32c18e3d876ec4acbb06c5daa326e45d81a65e4, closed.
