### ISSUE TITLE
Extraneous newline added when no temporary headers specified

### ISSUE THREAD

**Issue by ldionmarcil** [Quitten/Autorize#84]
Hi, I noticed that Autorize adds an extraneous newline at the end of requests when no temporary headers are added. My use case was changing a cookie's value, without adding a header. Below shows an example of a simple match/replace:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/1320868/157125224-a2940207-71cc-428b-8ea8-8721f8525e9e.png">

With this configuration, Autorize would perform the string replace, but then it would add a newline at the bottom of the request:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/1320868/157125342-b8bc580e-4729-47b9-a138-7c6222efde8d.png">

Needless to say, this newline creates undesirable behaviours where an application expects a simple GET, but instead receives a fat GET (GET with a POST body). See screenshot below for responses, for previous screenshot's requests:

<img width="907" alt="image" src="https://user-images.githubusercontent.com/1320868/157126523-1810599d-d384-4e48-b2b0-acb7d673c36b.png">

A current workaround is to add a dummy header, ie `Foo: Bar`, but I suppose many people won't figure this out until much debugging. Could this be fixed?

Burp: 2022.1.1
Autorize: BApp store version
Tested on two different machines

**Comment by terminalJunki3** [comment]
@ldionmarcil I was able to replicate this issue as well.  Doing a little bit of troubleshooting, I was able to determine that when the "Temporary Headers" are blank, this is when the extra new line appears. This might rule out that the match/replace is the problem. 

<img width="328" alt="image" src="https://user-images.githubusercontent.com/43526239/157249953-ca8633fc-72db-40d0-acd7-389ce2017087.png">

**Comment by ldionmarcil** [comment]
Hi @terminalJunki3, sorry if my initial message wasn't clear:

> [...] Autorize adds an extraneous newline at the end of requests when no temporary headers are added

you're correct, this occurs when the temporary headers are blank. The search & replace demonstration was merely to demonstrate that the extension otherwise works.

**Comment by terminalJunki3** [comment]
> Hi @terminalJunki3, sorry if my initial message wasn't clear:
> 
> > [...] Autorize adds an extraneous newline at the end of requests when no temporary headers are added
> 
> you're correct, this occurs when the temporary headers are blank. The search & replace demonstration was merely to showcase that the extension otherwise works.
@ldionmarcil Thank you sir for the clarification. I starting looking into this. Ill update this thread if I can find/add a fix.

**Comment by Quitten** [comment]
Fixed on https://github.com/Quitten/Autorize/commit/4e4d6f1508f45ab31fc8a3a38fcc57afdf187654 by @terminalJunki3 
@ldionmarcil  - please let me know if you still suffering this issue.
Closed.
