### ISSUE TITLE
[feature request] ^R --> to repeater

### ISSUE THREAD

**Issue by drwetter** [Quitten/Autorize#92]
Thanks for the useful extension!

What I miss is that in the request/response viewer tab I can't use ^R, i.e. continue working on on request in the repeater. I understand e.g. there are all requests there which authorize snooped and resubmitted and one can press ^R from the logger/logger++ window. It's just one step more.

Any reason for that?

If it's more than ~3 lines of code: Never mind.

Thanks, Dirk

**Comment by drwetter** [comment]
also popup actions like "copy URL" (or even "copy as cURL"), send to comparer would be useful. Don't know whether it's the same reason that those standard actions/popus aren't available?

**Comment by terminalJunki3** [comment]
> Thanks for the useful extension!
> 
> What I miss is that in the request/response viewer tab I can't use ^R, i.e. continue working on on request in the repeater. I understand e.g. there are all requests there which authorize snooped and resubmitted and one can press ^R from the logger/logger++ window. It's just one step more.
> 
> Any reason for that?
> 
> If it's more than ~3 lines of code: Never mind.
> 
> Thanks, Dirk

Quick question: is the ask that you would want to be able to press ^R to send to repeater?  I can look at the documentation this week and see what it entails.

**Comment by drwetter** [comment]
> Quick question: is the ask that you would want to be able to press ^R to send to repeater? I can look at the documentation this week and see what it entails.

For my workflow that would help a lot, maybe including like "copy to URL". 

Other's mileage may vary. ;-)

**Comment by terminalJunki3** [comment]
> > Quick question: is the ask that you would want to be able to press ^R to send to repeater? I can look at the documentation this week and see what it entails.
> 
> For my workflow that would help a lot, maybe including like "copy to URL".
> 
> Other's mileage may vary. ;-)

haha - Understood. Ill look for a solution 👍

**Comment by terminalJunki3** [comment]
@drwetter Happy new year.  I decided to implement this from scratch so that when control+r or command + r is pressed, it will send the currently selected row to repeater. Please see the pull request Send to repeater #104 @Quitten please let me know if you see any issues. Ty

**Comment by terminalJunki3** [comment]
@drwetter also added support to copy URL via shortcut keys

**Comment by Quitten** [comment]
@terminalJunki3 - Thank you very much! I reviewed your code and added few comments, will merge it once they are done

**Comment by Quitten** [comment]
Fixed on https://github.com/Quitten/Autorize/commit/b90159218e5f8e34661a6a7f473d15e70953f929
Closed, thanks for @terminalJunki3

**Comment by drwetter** [comment]
Thanks for your work, guys!
