### ISSUE TITLE
[Feature] Match Response Header in Interception Filters

### ISSUE THREAD

**Issue by tarunKoyalwar** [Quitten/Autorize#97]
Hii,

Currently autorize does not have a interception filter where it is possible to match certain headers in response . Currently I am working on  a program which responds with lot of HTML pages and any sensitive response returned by server is usually a JSON response . 

It would be great if autorize can intercept if content-type of response is `application/json` .

**Comment by terminalJunki3** [comment]
Hey @tarunKoyalwar, any chance you can add an example with a couple images to help highlight your use case?  That will help with the development process. Thanks!

**Comment by tarunKoyalwar** [comment]
As per my knowledge If a request should be ignored by Autorize or should be checked for IDOR depends on the given interception filters .

![interception_menu](https://user-images.githubusercontent.com/45962551/186767661-cdd6ec96-23e1-4e0e-afe2-33bdc4a5bb48.png)

Autorize does not have any interception filter option which matches response header . something like
`Matches Response Header` .

From my bug hunting experience I can tell that usually any user information or operation or graphql or any other useful information is returned in json . And usually IDOR exists in similar cases . 

Currently I have to use `URL Contains` and `URL Not Contains` regex mode to filter unnecessary requests from Autorize and I have to change these for each project . 

If a New Option `Matches Response Header` is added to Interception FIlters  matching a header like `Content-Type: application/json` would remove pointless requests to be sent to Autorize and reduce traffic .


Pls let me know if you need any other information @terminalJunki3  @Quitten

**Comment by terminalJunki3** [comment]
@tarunKoyalwar great explanation and supplemental information. Looking into a solution.

**Comment by terminalJunki3** [comment]
@tarunKoyalwar just submitted a pull request to update the filter names, but it looks like the functionality exists in the current code base.  I'm not sure what version you are running but if you pull this current project you should see something called "Header Contains" and "Header doesn't contain" in the inception filters. These are actually referring to the response headers, although it doesn't specify that, hence the submitted pull request. 

Please let me know if I can provide more clarity.

What it will look like
<img width="625" alt="image" src="https://user-images.githubusercontent.com/43526239/186910450-6d3dc211-0305-4dc6-ae1f-c44ab4067c56.png">

**Comment by tarunKoyalwar** [comment]
Apologies , It looks like I was using Autorize extension from Bapp Store . It is outdated!!
